version: 0.2

env:
  variables:
    FOO: "bar"
  parameter-store:
    ecr_ak: "China-ECR-AK"
    ecr_sk: "China-ECR-SK"

phases:
  install:
    runtime-versions: 
        docker: 18
  pre_build:
    commands:
      - echo "authenticate to Amazon ECR(cn-northwest-1)"
      - bash ./mirror/ECR_Auth.sh
  build:
    commands:
      - cd mirror; bash mirror-images-daily.sh
  post_build:
    commands:
      - echo "post_build phase"
artifacts:
  # files: 
  discard-paths: yes
